services:
  - type: web
    name: keg-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: FLASK_DEBUG
        value: ""
      # Set this to your Postgres connection string, e.g. postgresql://user:pass@host/db
      - key: DATABASE_URL
        sync: false
